version: "3.9"

services:
  openresty:
    build: .
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./data:/data
      - /etc/hosts:/etc/hosts:ro
    environment:
      - LICENSE_KEY=${LICENSE_KEY}
